name: Terraform AWS CI-CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Configure AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/testingdummy
          aws-region: ap-south-1

      # 4. Check AWS identity
      - name: Check AWS identity
        run: aws sts get-caller-identity

      # 5. Terraform Format
      - name: Terraform Format Check
        run: terraform fmt 

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        env:
          TF_VAR_transit_gateway_id: ${{ secrets.TG_TRANSIT_GATEWAY_ID }}
          TF_VAR_ram_resource_share_arn: ${{ secrets.RAM_RESOURCE_SHARE_ARN }}

          TF_VAR_subnets: |
            {
              "private_1": {
                "cidr_block": "10.1.0.0/24",
                "az": "ap-south-1a"
              },
              "private_2": {
                "cidr_block": "10.1.1.0/24",
                "az": "ap-south-1b"
              }
            }

        run: terraform plan -input=false
         
      # 9. Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_transit_gateway_id: ${{ secrets.TG_TRANSIT_GATEWAY_ID }}
          TF_VAR_ram_resource_share_arn: ${{ secrets.RAM_RESOURCE_SHARE_ARN }}

          TF_VAR_subnets: |
            {
              "private_1": {
                "cidr_block": "10.1.0.0/24",
                "az": "ap-south-1a"
              },
              "private_2": {
                "cidr_block": "10.1.1.0/24",
                "az": "ap-south-1b"
              }
            }

        run: terraform apply -auto-approve -input=false              